version: '3'

services:
  cmdr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r3bl-cmdr
    volumes: [ ]
      # Mount your local directory to the container for development
      # Uncomment and modify the paths as needed
    # - ../:/app/project
    # If your application exposes ports, you can uncomment and configure them
    # ports:
    #   - "8080:8080"
    # If your application needs environment variables, you can add them here
    # environment:
    #   - VAR_NAME=value
    # If you want the container to restart automatically
    restart: unless-stopped