#!/usr/bin/env fish

# Import shared toolchain utilities
source script_lib.fish

# Rust Toolchain Update Script
#
# Purpose: Automatically finds and installs a stable Rust nightly toolchain,
#          biasing toward the latest nightly (today's snapshot) as most stable.
#          Falls back to older versions only if ICE (Internal Compiler Error) detected.
#          Validates each candidate toolchain by running comprehensive tests.
#          Also performs aggressive cleanup to save disk space.
#
# Smart Validation Strategy:
# - Search window: today → 45 days ago (46 total candidates)
# - Philosophy: Latest nightly is usually most stable with newest bug fixes
# - Start with today's nightly snapshot (optimistic approach)
# - For each candidate: UPDATE rust-toolchain.toml, THEN run validation suite
# - Validation tests production scenario: clippy, build, tests, doctests, docs
# - Check for ICE (Internal Compiler Errors) - indicates toolchain bugs
# - If ICE detected, try progressively older nightlies until finding stable one
# - Distinguish between toolchain issues (ICE) vs code issues (compilation/test failures)
# - Once stable toolchain found, rust-toolchain.toml is already configured correctly
# - Send desktop notifications (notify-send): success when found, critical alert if all fail
#
# Cleanup Strategy:
# - Keep only: stable-* + the validated nightly-YYYY-MM-DD
# - Remove: all other nightly toolchains, including generic "nightly"
# - Installs rust-analyzer and rust-src components (required by VSCode, RustRover, Claude Code, and cargo)
# - Installs x86_64-pc-windows-gnu target for cross-platform verification
#
# Final Verification:
# - Remove ICE failure files (rustc-ice-*.txt) generated during validation
# - Clean all caches: cargo cache, build artifacts (cargo clean)
# - Run full verification build with new toolchain:
#   - cargo test --all-targets
#   - cargo test --doc
#   - cargo doc --no-deps
# - Ensures new toolchain works perfectly with fresh build from scratch
#
# Cargo Tools Update:
# - Updates all cargo development tools (bacon, flamegraph, etc.)
# - Uses cargo install-update to check and install latest versions
# - Keeps development tools current with bug fixes and features
# - Non-blocking: continues even if some tool updates fail
#
# Concurrency Safety:
# - Uses mkdir (atomic directory creation) for mutual exclusion
# - Atomic lock: check-and-create happens in ONE kernel operation (only one process succeeds)
# - Safe to run alongside other toolchain scripts - they'll queue or abort gracefully
# - Stale lock detection: Automatically removes locks older than 10 minutes (crashed processes)
#
# This script is designed to run weekly via systemd timer.

# ============================================================================
# Global Variables
# ============================================================================

set -g LOG_FILE $HOME/Downloads/rust-toolchain-update.log
set -g PROJECT_DIR (pwd)
set -g TOOLCHAIN_FILE $PROJECT_DIR/rust-toolchain.toml
set -g target_toolchain ""

# ============================================================================
# Script-Specific Functions
# ============================================================================
# Note: Common helper functions (logging, validation, state management, component
# installation) are now in script_lib.fish with toolchain_* prefix.
# ============================================================================

# Cross-platform helper to get a date X days ago
# macOS uses BSD date with -v flag, Linux uses GNU date with -d flag
function get_date_days_ago
    set -l days_ago $argv[1]
    if test (uname) = "Darwin"
        # macOS: use -v flag (e.g., -v-5d for 5 days ago)
        date -v-{$days_ago}d "+%Y-%m-%d"
    else
        # Linux: use -d flag
        date -d "$days_ago days ago" "+%Y-%m-%d"
    end
end

function clean_and_verify_build
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Cleaning all caches and build artifacts"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    cd $PROJECT_DIR

    # Remove ICE failure text files generated by rustc
    toolchain_log "Removing any ICE failure files (rustc-ice-*.txt)..."
    find $PROJECT_DIR -name "rustc-ice-*.txt" -type f -delete 2>/dev/null
    toolchain_log "✅ ICE files cleaned"
    toolchain_log ""

    # Clean build artifacts
    toolchain_log ""
    if not toolchain_log_command "Running cargo clean..." cargo clean
        toolchain_log "⚠️  cargo clean failed (non-critical)"
    end

    toolchain_log ""
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Running full build and test verification"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    # Run tests with cargo test
    toolchain_log "Running cargo test --all-targets..."
    if not toolchain_log_command "Running tests..." cargo test --all-targets
        toolchain_log "⚠️  Some tests failed (this might be expected)"
    else
        toolchain_log "✅ All tests passed"
    end

    # Run doctests
    toolchain_log ""
    toolchain_log "Running cargo test --doc..."
    if not toolchain_log_command "Running doctests..." cargo test --doc
        toolchain_log "⚠️  Some doctests failed (this might be expected)"
    else
        toolchain_log "✅ All doctests passed"
    end

    # Build documentation
    toolchain_log ""
    toolchain_log "Running cargo doc --no-deps..."
    if not toolchain_log_command "Building documentation..." cargo doc --no-deps
        toolchain_log "⚠️  Documentation build had warnings/errors"
    else
        toolchain_log "✅ Documentation built successfully"
    end

    toolchain_log ""
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Clean and verify completed"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""
end

# ============================================================================
# Core Logic Functions
# ============================================================================

function validate_toolchain
    set -l toolchain $argv[1]
    set -l temp_output /tmp/rust-toolchain-validation-(date +%s).log

    toolchain_log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    toolchain_log "Validating toolchain: $toolchain"
    toolchain_log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    cd $PROJECT_DIR

    # Update rust-toolchain.toml with candidate toolchain
    toolchain_log "Updating rust-toolchain.toml to test candidate toolchain..."
    if not set_toolchain_in_toml $toolchain
        toolchain_log "❌ Failed to update rust-toolchain.toml with candidate toolchain"
        return 1
    end
    toolchain_log "✅ rust-toolchain.toml updated with: $toolchain"
    toolchain_log ""

    # List of validation commands to verify toolchain stability
    # Validation tests the production scenario where cargo reads rust-toolchain.toml
    # We're checking for ICE (Internal Compiler Errors), not code correctness
    set -l validation_steps \
        "clippy:cargo clippy --all-targets" \
        "build-prod-code:cargo build" \
        "build-test-code:cargo test --no-run" \
        "tests:cargo test --all-targets" \
        "doctest:cargo test --doc" \
        "doc:cargo doc --no-deps"

    # Run each validation step
    for step in $validation_steps
        set -l step_name (string split ":" $step)[1]
        set -l step_cmd (string split ":" $step)[2]

        toolchain_log ""
        toolchain_log "Running validation step: $step_name"
        toolchain_log "Command: $step_cmd"

        # Run command and capture output
        eval $step_cmd > $temp_output 2>&1
        set -l exit_code $status

        # Check for ICE patterns (Internal Compiler Error indicators)
        # These indicate toolchain problems, not code problems
        if grep -Ei "internal compiler error|thread 'rustc' panicked|error: the compiler unexpectedly panicked|this is a bug in the rust compiler" $temp_output > /dev/null
            toolchain_log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            toolchain_log "❌ ICE DETECTED in $step_name"
            toolchain_log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            toolchain_log "Toolchain $toolchain is UNSTABLE (ICE detected)"
            toolchain_log ""
            toolchain_log "Command output (last 50 lines):"
            tail -n 50 $temp_output | tee -a $LOG_FILE
            command rm -f $temp_output
            return 1  # ICE detected - toolchain is bad
        end

        # Log exit code (non-zero is OK if it's just compilation/test errors)
        if test $exit_code -ne 0
            toolchain_log "  ⚠️  Command exited with code $exit_code (this is OK if not ICE)"
            toolchain_log "  Checking if failure is due to code issues (not toolchain)..."
            # If we got here, no ICE was detected, so it's a code issue
            toolchain_log "  ✅ No ICE detected - continuing validation"
        else
            toolchain_log "  ✅ Command succeeded (exit: $exit_code)"
        end
    end

    command rm -f $temp_output
    toolchain_log ""
    toolchain_log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    toolchain_log "✅ Toolchain $toolchain is STABLE (no ICE detected)"
    toolchain_log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    toolchain_log ""
    return 0  # Toolchain is stable
end

function find_stable_toolchain
    set -l search_window_days 45  # Search from today back to 45 days ago (46 total attempts including today)

    # Clear rustup caches to prevent stale download/temp file issues during validation
    toolchain_log "Clearing rustup download and temp caches..."
    command rm -rf ~/.rustup/downloads/
    command rm -rf ~/.rustup/tmp/
    toolchain_log "✅ Rustup caches cleared"
    toolchain_log ""

    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Starting search for stable toolchain"
    toolchain_log "Strategy: Start with today's snapshot, try progressively older up to $search_window_days days ago"
    toolchain_log "Search window: "(date "+%Y-%m-%d")" to "(get_date_days_ago $search_window_days)
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    for i in (seq 0 $search_window_days)
        set -l days_ago $i

        # Calculate the target date
        set -l target_date (get_date_days_ago $days_ago)
        set -l candidate_toolchain "nightly-$target_date"

        toolchain_log "═══════════════════════════════════════════════════════"
        toolchain_log "Attempt "(math $i + 1)"/"(math $search_window_days + 1)
        toolchain_log "Trying toolchain: $candidate_toolchain ($days_ago days ago)"
        toolchain_log "═══════════════════════════════════════════════════════"
        toolchain_log ""

        # Install the candidate toolchain
        toolchain_log "Installing candidate toolchain: $candidate_toolchain"
        if not rustup toolchain install $candidate_toolchain 2>&1 | tee -a $LOG_FILE
            toolchain_log "❌ Failed to install $candidate_toolchain"
            toolchain_log "Trying next candidate..."
            toolchain_log ""
            continue
        end

        toolchain_log "✅ Successfully installed $candidate_toolchain"
        toolchain_log ""

        # Validate the toolchain using internal validation function
        # This updates rust-toolchain.toml and runs the full validation suite
        if validate_toolchain $candidate_toolchain
            # Found a stable toolchain!
            set -g target_toolchain $candidate_toolchain
            toolchain_log "═══════════════════════════════════════════════════════"
            toolchain_log "🎉 FOUND STABLE TOOLCHAIN: $candidate_toolchain"
            toolchain_log "═══════════════════════════════════════════════════════"
            toolchain_log ""

            return 0
        else
            toolchain_log "Toolchain $candidate_toolchain is unstable (ICE detected)"
            toolchain_log "Will try an older toolchain..."
            toolchain_log ""

            # Uninstall the bad toolchain to save space
            toolchain_log "Uninstalling unstable toolchain: $candidate_toolchain"
            rustup toolchain uninstall $candidate_toolchain 2>&1 | tee -a $LOG_FILE
            toolchain_log ""
        end
    end

    # If we get here, we couldn't find a stable toolchain
    set -l total_attempts (math $search_window_days + 1)
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "❌ ERROR: Could not find stable toolchain"
    toolchain_log "Tried $total_attempts candidates (from "(date "+%Y-%m-%d")" back to "(get_date_days_ago $search_window_days)")"
    toolchain_log "All tested nightlies had ICE errors or failed to install"
    toolchain_log "═══════════════════════════════════════════════════════"

    # Send system notification (cross-platform: macOS and Linux)
    send_system_notification \
        "Rust Toolchain Update Failed" \
        "Could not find stable nightly in $total_attempts attempts ($search_window_days-day window). Check log: $LOG_FILE" \
        "critical"
    toolchain_log "System notification sent"

    return 1
end

function update_toolchain_config
    toolchain_log "Updating rust-toolchain.toml to use $target_toolchain..."

    if not set_toolchain_in_toml $target_toolchain
        toolchain_log "❌ Failed to update rust-toolchain.toml"
        return 1
    end

    toolchain_log "✅ Successfully updated rust-toolchain.toml"

    # Show the updated content
    toolchain_log "Updated rust-toolchain.toml content:"
    cat $TOOLCHAIN_FILE | tee -a $LOG_FILE

    return 0
end

function cleanup_old_toolchains
    # Get disk usage before cleanup
    toolchain_log "Checking disk usage before cleanup..."
    set -l before_size (du -sh ~/.rustup/toolchains 2>/dev/null | cut -f1)
    toolchain_log "Toolchains directory size before cleanup: $before_size"

    # List all currently installed toolchains
    toolchain_log "Currently installed toolchains:"
    set -l all_toolchains (rustup toolchain list | cut -d' ' -f1)
    for toolchain in $all_toolchains
        toolchain_log "  - $toolchain"
    end

    # Cleanup old toolchains - keep only stable and our target nightly
    toolchain_log "Starting aggressive toolchain cleanup..."
    set -l removed_count 0

    for toolchain in $all_toolchains
        # Keep stable toolchains
        if string match -q "stable-*" $toolchain
            toolchain_log "  KEEPING: $toolchain (stable)"
            continue
        end

        # Keep our target nightly
        if string match -q "$target_toolchain*" $toolchain
            toolchain_log "  KEEPING: $toolchain (target nightly)"
            continue
        end

        # Remove everything else (old nightlies, generic nightly, etc.)
        toolchain_log "  REMOVING: $toolchain"
        if rustup toolchain uninstall $toolchain 2>&1 | tee -a $LOG_FILE
            set removed_count (math $removed_count + 1)
            toolchain_log "    ✅ Successfully removed $toolchain"
        else
            toolchain_log "    ❌ Failed to remove $toolchain"
        end
    end

    toolchain_log "Removed $removed_count old toolchain(s)"

    # Get disk usage after cleanup
    toolchain_log "Checking disk usage after cleanup..."
    set -l after_size (du -sh ~/.rustup/toolchains 2>/dev/null | cut -f1)
    toolchain_log "Toolchains directory size after cleanup: $after_size"

    return 0
end

# ============================================================================
# Main Function
# ============================================================================

function main
    # Truncate log file at start of script so each run gets a fresh log
    echo -n "" > $LOG_FILE

    # Acquire lock before proceeding
    if not acquire_toolchain_lock
        return 1
    end

    # Initialize
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Rust Toolchain Update Started at "(date)
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    # Output log file location to stdout for user visibility
    echo ""
    echo "📋 Detailed log: $LOG_FILE"
    echo ""

    # Execute workflow
    toolchain_validate_prerequisites
    or begin
        release_toolchain_lock
        return 1
    end

    toolchain_show_current_state

    # Find a stable toolchain (with ICE validation)
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Phase 1: Find Stable Toolchain"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    find_stable_toolchain
    or begin
        toolchain_log "❌ FATAL: Could not find a stable toolchain"
        toolchain_log "Please check the log file for details: $LOG_FILE"
        release_toolchain_lock
        return 1
    end

    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Phase 2: Install Components"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    # Note: rust-toolchain.toml was already updated during validation
    toolchain_log "✅ rust-toolchain.toml already updated during validation"

    # Note: No need to install again - find_stable_toolchain already installed it
    toolchain_log "✅ Toolchain $target_toolchain already installed"

    # Install rust-analyzer component
    toolchain_install_rust_analyzer
    or begin
        release_toolchain_lock
        return 1
    end

    # Install additional components (rust-src for IDE support)
    toolchain_install_additional_components

    # Install Windows cross-compilation target for verifying platform-specific code
    install_windows_target

    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Phase 3: Cleanup Old Toolchains"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    cleanup_old_toolchains

    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Phase 4: Verify Final State"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    toolchain_verify_final_state

    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Phase 5: Clean Caches and Full Verification Build"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    clean_and_verify_build

    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "Phase 6: Update Stable Toolchain and Cargo Development Tools"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    # Update stable toolchain to latest version
    toolchain_log "Updating stable toolchain to latest version..."
    if rustup update stable 2>&1 | tee -a $LOG_FILE
        toolchain_log "✅ Stable toolchain updated successfully"
    else
        toolchain_log "⚠️  Stable toolchain update had issues (non-critical, continuing)"
    end
    toolchain_log ""

    # Update all cargo tools (bacon, flamegraph, etc.)
    toolchain_log "Updating cargo development tools to latest versions..."
    if fish run.fish update-cargo-tools 2>&1 | tee -a $LOG_FILE
        toolchain_log "✅ Cargo tools updated successfully"
    else
        toolchain_log "⚠️  Cargo tools update had issues (non-critical, continuing)"
    end
    toolchain_log ""

    # Release lock after successful completion
    release_toolchain_lock

    # Cleanup
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log "✅ Rust Toolchain Update Completed at "(date)
    toolchain_log "Final toolchain: $target_toolchain"
    toolchain_log "═══════════════════════════════════════════════════════"
    toolchain_log ""

    # Send final success notification (cross-platform: macOS and Linux)
    send_system_notification \
        "Rust Toolchain Update Complete" \
        "✅ Successfully updated to: $target_toolchain. All validation, cleanup, and verification passed" \
        "normal"
    toolchain_log "Final success notification sent"

    return 0
end

# ============================================================================
# Script Entry Point
# ============================================================================

# Run main function and exit with its status
main
exit $status