// Copyright (c) 2022-2025 R3BL LLC. Licensed under Apache License, Version 2.0.

//! Terminal output operations for backend/execution layer.
//!
//! # You Are Here: **Stage 4-5 Data Type**
//!
//! ```text
//! [Stage 4: Backend Converter]
//!   ↓ generates
//! RenderOpOutput ← YOU ARE HERE
//!   ↓ consumed by
//! [Stage 5: Backend Executor]
//! ```
//!
//! <div class="warning">
//!
//! **For the complete 6-stage rendering pipeline with visual diagrams and stage
//! reference table**, see the [rendering pipeline overview].
//!
//! </div>
//!
//! # Type Safety & Semantic Boundary
//!
//! This enum type ensures only Output-appropriate operations are used in backend code.
//! Operations like [`CompositorNoClipTruncPaintTextWithAttributes`] (which assumes
//! clipping is already done) cannot be accidentally used in component code.
//!
//! # Context
//!
//! These operations are optimized for terminal execution. They're generated by backend
//! converters (Stage 4) after processing IR and don't require additional clipping or
//! validation. Only `RenderOpOutputVec` implements the [`RenderOpsExec`] trait,
//! preventing IR from being executed directly and bypassing the Compositor.
//!
//! [`CompositorNoClipTruncPaintTextWithAttributes`]: crate::render_op::RenderOpOutput::CompositorNoClipTruncPaintTextWithAttributes
//! [rendering pipeline overview]: mod@crate::terminal_lib_backends#rendering-pipeline-architecture

use super::{RenderOpCommon, RenderOpsExec};
use crate::{InlineString, LockedOutputDevice, RenderOpsLocalData, Size,
            TERMINAL_LIB_BACKEND, TerminalLibBackend, TuiStyle, ok,
            terminal_lib_backends::{crossterm_backend::PaintRenderOpImplCrossterm,
                                    direct_to_ansi::RenderOpPaintImplDirectToAnsi}};
use std::{fmt::{Debug, Formatter, Result},
          ops::{AddAssign, Deref, DerefMut}};

/// Terminal output operations for backend/execution layer.
///
/// These operations are optimized for terminal execution. They are generated by backend
/// converters (e.g., [`OfsBufPaint`]) after processing the IR and don't require
/// additional clipping or validation.
///
/// # Type Safety
///
/// This enum type ensures that only Output-appropriate operations are used in backend
/// code. Operations like [`CompositorNoClipTruncPaintTextWithAttributes`] (which assumes
/// clipping is already done) cannot be accidentally used in component code.
///
/// [`CompositorNoClipTruncPaintTextWithAttributes`]:
///     crate::render_op::RenderOpOutput::CompositorNoClipTruncPaintTextWithAttributes
/// [`OfsBufPaint`]: crate::OfsBufPaint
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderOpOutput {
    /// Shared operation used identically in IR and Output contexts.
    Common(RenderOpCommon),

    /// Paint text without clipping/truncation (already handled by compositor).
    ///
    /// **Internal use only** - this operation is used by backend converters
    /// after the `OfsBuf` has been fully processed. The compositor has
    /// already handled:
    /// - Clipping text to available width
    /// - Unicode and emoji display width
    /// - Style application
    ///
    /// The backend just needs to paint the result as-is to the terminal.
    CompositorNoClipTruncPaintTextWithAttributes(InlineString, Option<TuiStyle>),
}

/// Collection of terminal output operations for backend rendering.
///
/// This type wraps `RenderOpOutput` values and provides ergonomic collection methods.
/// Used by backend converters and the terminal execution layer.
#[derive(Clone, Default, PartialEq, Eq)]
pub struct RenderOpOutputVec {
    pub list: Vec<RenderOpOutput>,
}

impl RenderOpOutputVec {
    /// Creates a new empty collection of output operations.
    #[must_use]
    pub fn new() -> Self { Self { list: Vec::new() } }

    /// Add a single operation to the collection.
    pub fn push(&mut self, arg_op: impl Into<RenderOpOutput>) {
        self.list.push(arg_op.into());
    }

    /// Add multiple operations to the collection.
    pub fn extend(&mut self, ops: impl IntoIterator<Item = RenderOpOutput>) {
        self.list.extend(ops);
    }

    /// Gets the number of operations in the collection.
    #[must_use]
    pub fn len(&self) -> usize { self.list.len() }

    /// Checks if the collection is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool { self.list.is_empty() }

    /// Iterate over the operations.
    pub fn iter(&self) -> impl Iterator<Item = &RenderOpOutput> { self.list.iter() }

    /// Routes a single Output render operation to the appropriate backend implementation.
    ///
    /// This is a private helper for the [`ExecutableRenderOps::execute_all()`] trait
    /// method. It acts as a dispatcher, selecting the correct terminal library
    /// backend (Crossterm or `DirectAnsi`) and delegating the actual rendering work.
    ///
    /// # Arguments
    /// - `render_local_data`: Shared mutable state for optimization
    ///   - Tracks current cursor position and colors
    ///   - Allows skipping redundant commands
    /// - `render_op_output`: The specific output operation to execute
    ///   - Evaluated by the backend to determine precise terminal commands
    /// - `window_size`: Current terminal window dimensions
    ///   - Used for bounds checking to prevent off-screen rendering
    /// - `locked_output_device`: Thread-safe access to terminal output
    ///   - Backend queues commands to this output device
    fn route_paint_render_op_output_to_backend(
        render_local_data: &mut RenderOpsLocalData,
        render_op_output: &RenderOpOutput,
        window_size: Size,
        locked_output_device: LockedOutputDevice<'_>,
    ) {
        match TERMINAL_LIB_BACKEND {
            TerminalLibBackend::Crossterm => match render_op_output {
                RenderOpOutput::Common(common_op) => {
                    PaintRenderOpImplCrossterm {}.paint_common(
                        common_op,
                        window_size,
                        render_local_data,
                        locked_output_device,
                    );
                }
                RenderOpOutput::CompositorNoClipTruncPaintTextWithAttributes(
                    text,
                    style,
                ) => {
                    PaintRenderOpImplCrossterm::paint_text_with_attributes(
                        text,
                        *style,
                        window_size,
                        render_local_data,
                        locked_output_device,
                    );
                }
            },
            TerminalLibBackend::DirectToAnsi => match render_op_output {
                RenderOpOutput::Common(common_op) => {
                    RenderOpPaintImplDirectToAnsi {}.paint_common(
                        common_op,
                        window_size,
                        render_local_data,
                        locked_output_device,
                    );
                }
                RenderOpOutput::CompositorNoClipTruncPaintTextWithAttributes(
                    text,
                    style,
                ) => {
                    RenderOpPaintImplDirectToAnsi::paint_text_with_attributes(
                        text,
                        *style,
                        window_size,
                        render_local_data,
                        locked_output_device,
                    );
                }
            },
        }
    }
}

impl From<RenderOpCommon> for RenderOpOutput {
    fn from(op: RenderOpCommon) -> Self { RenderOpOutput::Common(op) }
}

impl Deref for RenderOpOutputVec {
    type Target = Vec<RenderOpOutput>;

    fn deref(&self) -> &Self::Target { &self.list }
}

impl DerefMut for RenderOpOutputVec {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.list }
}

/// Ergonomic operator for adding a single operation to the collection.
///
/// This allows using the `+=` operator instead of `.push()` for more readable and
/// concise code. The `Into<RenderOpOutput>` conversion is automatically applied, so types
/// like `RenderOpCommon` can be used directly.
///
/// # Example
///
/// ```
/// # use r3bl_tui::{RenderOpCommon, RenderOpOutputVec, RenderOpOutput, Pos, row, col};
/// let mut render_ops = RenderOpOutputVec::new();
///
/// // Using += operator (more ergonomic)
/// render_ops += RenderOpOutput::Common(RenderOpCommon::MoveCursorPositionAbs(Pos::new((row(5), col(10)))));
///
/// assert_eq!(render_ops.len(), 1);
/// ```
impl AddAssign<RenderOpOutput> for RenderOpOutputVec {
    fn add_assign(&mut self, rhs: RenderOpOutput) { self.list.push(rhs); }
}

impl AddAssign<RenderOpCommon> for RenderOpOutputVec {
    fn add_assign(&mut self, rhs: RenderOpCommon) {
        self.list.push(RenderOpOutput::Common(rhs));
    }
}

impl AddAssign<RenderOpOutput> for &mut RenderOpOutputVec {
    fn add_assign(&mut self, rhs: RenderOpOutput) { self.list.push(rhs); }
}

impl AddAssign<RenderOpCommon> for &mut RenderOpOutputVec {
    fn add_assign(&mut self, rhs: RenderOpCommon) {
        self.list.push(RenderOpOutput::Common(rhs));
    }
}

impl Debug for RenderOpOutputVec {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        const DELIM: &str = "\n  - ";

        let mut iter = self.iter();

        // We don't care about the result of this operation.
        f.write_str("RenderOpOutputVec.len(): ").ok();

        write!(f, "{}", self.list.len()).ok();

        // First line.
        if let Some(first) = iter.next() {
            // We don't care about the result of this operation.
            f.write_str("[").ok();

            write!(f, "{first:?}").ok();

            f.write_str("]").ok();
        }

        // Subsequent lines.
        for item in iter {
            // We don't care about the result of this operation.
            f.write_str(DELIM).ok();

            f.write_str("[").ok();

            write!(f, "{item:?}").ok();

            f.write_str("]").ok();
        }

        ok!()
    }
}

impl RenderOpsExec for RenderOpOutputVec {
    fn execute_all(
        &self,
        window_size: Size,
        locked_output_device: LockedOutputDevice<'_>,
    ) {
        let mut render_local_data = RenderOpsLocalData::default();
        for render_op_output in &self.list {
            RenderOpOutputVec::route_paint_render_op_output_to_backend(
                &mut render_local_data,
                render_op_output,
                window_size,
                locked_output_device,
            );
        }
    }
}

impl From<Vec<RenderOpOutput>> for RenderOpOutputVec {
    fn from(ops: Vec<RenderOpOutput>) -> Self { Self { list: ops } }
}

impl FromIterator<RenderOpOutput> for RenderOpOutputVec {
    fn from_iter<I: IntoIterator<Item = RenderOpOutput>>(iter: I) -> Self {
        Self {
            list: iter.into_iter().collect(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add_assign_single_op_via_render_op_output() {
        let mut render_ops = RenderOpOutputVec::new();

        assert_eq!(render_ops.len(), 0);

        // Add a single RenderOpOutput variant
        let op = RenderOpOutput::Common(RenderOpCommon::ClearScreen);

        render_ops += op.clone();

        assert_eq!(render_ops.len(), 1);

        assert_eq!(render_ops[0], op);
    }

    #[test]
    fn test_add_assign_converts_render_op_common_to_output() {
        let mut render_ops = RenderOpOutputVec::new();

        // Add via Into conversion from RenderOpCommon
        let op_common = RenderOpCommon::ResetColor;
        render_ops += RenderOpOutput::Common(op_common.clone());

        assert_eq!(render_ops.len(), 1);

        match &render_ops[0] {
            RenderOpOutput::Common(RenderOpCommon::ResetColor) => {
                // Test passed - the operation was converted and stored correctly
            }
            _ => panic!("Expected ResetColor"),
        }
    }

    #[test]
    fn test_add_assign_multiple_operations() {
        let mut render_ops = RenderOpOutputVec::new();

        // Add multiple operations using += operator
        let op1 = RenderOpCommon::ClearScreen;
        let op2 = RenderOpCommon::ResetColor;
        let op3 = RenderOpCommon::ClearScreen;

        render_ops += RenderOpOutput::Common(op1);
        render_ops += RenderOpOutput::Common(op2);
        render_ops += RenderOpOutput::Common(op3);

        assert_eq!(render_ops.len(), 3);
    }

    #[test]
    fn test_add_assign_vs_push_are_equivalent() {
        let mut render_ops_push = RenderOpOutputVec::new();

        let mut render_ops_add_assign = RenderOpOutputVec::new();

        let op = RenderOpCommon::ClearScreen;

        // Using push (which accepts Into<RenderOpOutput>)
        render_ops_push.push(op.clone());

        // Using += operator (note: RenderOpCommon implements Into<RenderOpOutput>)
        render_ops_add_assign += RenderOpOutput::Common(op);

        // Both should produce the same result
        assert_eq!(render_ops_push.len(), render_ops_add_assign.len());

        assert_eq!(render_ops_push[0], render_ops_add_assign[0]);
    }

    #[test]
    fn test_add_assign_is_ergonomic() {
        let mut render_ops = RenderOpOutputVec::new();

        // This demonstrates the ergonomic improvement over .push()
        // Push accepts Into<RenderOpOutput>, so RenderOpCommon works directly
        render_ops.push(RenderOpCommon::ClearScreen);

        assert_eq!(render_ops.len(), 1);
    }

    #[test]
    fn test_push_and_add_assign_work_together() {
        let mut render_ops = RenderOpOutputVec::new();

        // Mix push() and += operator
        // push() accepts Into<RenderOpOutput>, but += expects RenderOpOutput directly
        render_ops.push(RenderOpCommon::ClearScreen);

        render_ops += RenderOpOutput::Common(RenderOpCommon::ResetColor);

        render_ops.push(RenderOpCommon::ClearScreen);

        assert_eq!(render_ops.len(), 3);
    }

    #[test]
    fn test_add_assign_render_op_common_directly() {
        let mut render_ops = RenderOpOutputVec::new();

        // Add RenderOpCommon directly without wrapping in RenderOpOutput::Common
        render_ops += RenderOpCommon::ClearScreen;
        render_ops += RenderOpCommon::ResetColor;
        render_ops += RenderOpCommon::ClearScreen;

        assert_eq!(render_ops.len(), 3);

        // Verify the operations were wrapped correctly
        match &render_ops[0] {
            RenderOpOutput::Common(RenderOpCommon::ClearScreen) => {
                // First operation is correct
            }
            _ => panic!("Expected ClearScreen at index 0"),
        }
    }
}
