// Copyright (c) 2025 R3BL LLC. Licensed under Apache License, Version 2.0.

//! # Testing with Generated [`ANSI`] Sequences
//!
//! This test module uses **generated byte sequences** from the input sequence generator
//! to ensure comprehensive testing of the system's real-world usage pattern:
//!
//! 1. **Real-world integration**: Tests that our generator produces valid sequences our
//!    parser can consume (production usage pattern)
//! 2. **Scalability**: Easy to test many input combinations without hardcoding
//! 3. **Consistency**: Uses the same generator as all other [`PTY`] tests
//!
//! Protocol conformance is validated separately in [`validation_tests`] using hardcoded
//! sequences to ensure compliance with the [`VT-100`] spec.
//!
//! See the [parent module documentation] for full testing philosophy.
//!
//! # Run with:
//!
//! ```bash
//! cargo test -p r3bl_tui test_pty_mouse_events -- --nocapture
//! ```
//!
//! [`ANSI`]: https://en.wikipedia.org/wiki/ANSI_escape_code
//! [`PTY`]: https://en.wikipedia.org/wiki/Pseudoterminal
//! [`validation_tests`]: mod@crate::vt_100_terminal_input_parser::validation_tests
//! [`VT-100`]: https://vt100.net/docs/vt100-ug/chapter3.html
//! [parent module documentation]: mod@super#testing-philosophy

use crate::{MSG_CONTROLLED_READY, MSG_CONTROLLED_STARTING, GLYPH_CONTROLLED, GLYPH_CONTROLLER,
            GLYPH_CONTROLLER_CLEANUP, GLYPH_SUCCESS, GLYPH_WAITING,
            InputEvent, MSG_TEST_RUNNING, PtyTestContext, PtyTestMode, TermPos,
            core::ansi::{generator::generate_keyboard_sequence,
                         vt_100_terminal_input_parser::ir_event_types::{VT100InputEventIR,
                                                                        VT100KeyModifiersIR,
                                                                        VT100MouseActionIR,
                                                                        VT100MouseButtonIR}},
            generate_pty_test,
            tui::terminal_lib_backends::direct_to_ansi::DirectToAnsiInputDevice};
use std::{io::Write,
          time::Duration};

generate_pty_test! {
    test_fn: test_pty_mouse_events,
    controller: controller,
    controlled: controlled,
    mode: PtyTestMode::Raw,
}

/// [`PTY`] Controller: Send mouse event sequences and verify parsing
///
/// [`PTY`]: https://en.wikipedia.org/wiki/Pseudoterminal
#[allow(clippy::too_many_lines)]
fn controller(context: PtyTestContext) {
    let PtyTestContext {
        pty_pair,
        child,
        mut buf_reader,
        mut writer,
    } = context;

    eprintln!("{GLYPH_CONTROLLER} PTY Controller: Starting mouse events test...");
    eprintln!(
        "{GLYPH_WAITING} PTY Controller: Waiting for controlled process to start..."
    );

    // Wait for controlled to confirm it's running and ready.
    child
        .wait_for_ready(&mut buf_reader, MSG_CONTROLLED_READY)
        .expect("Failed to wait for ready signal");

    // Generate test cases using abstractions (no magic strings!)
    let mouse_events: Vec<(&str, VT100InputEventIR)> = vec![
        ("Left Click", VT100InputEventIR::Mouse {
            button: VT100MouseButtonIR::Left,
            pos: TermPos::from_one_based(10, 5),
            action: VT100MouseActionIR::Press,
            modifiers: VT100KeyModifiersIR::default(),
        }),
        ("Left Release", VT100InputEventIR::Mouse {
            button: VT100MouseButtonIR::Left,
            pos: TermPos::from_one_based(10, 5),
            action: VT100MouseActionIR::Release,
            modifiers: VT100KeyModifiersIR::default(),
        }),
        ("Right Click", VT100InputEventIR::Mouse {
            button: VT100MouseButtonIR::Right,
            pos: TermPos::from_one_based(20, 10),
            action: VT100MouseActionIR::Press,
            modifiers: VT100KeyModifiersIR::default(),
        }),
        ("Middle Click", VT100InputEventIR::Mouse {
            button: VT100MouseButtonIR::Middle,
            pos: TermPos::from_one_based(30, 15),
            action: VT100MouseActionIR::Press,
            modifiers: VT100KeyModifiersIR::default(),
        }),
        ("Scroll Up", VT100InputEventIR::Mouse {
            button: VT100MouseButtonIR::Left,
            pos: TermPos::from_one_based(25, 12),
            action: VT100MouseActionIR::Scroll(crate::core::ansi::vt_100_terminal_input_parser::VT100ScrollDirectionIR::Up),
            modifiers: VT100KeyModifiersIR::default(),
        }),
        ("Scroll Down", VT100InputEventIR::Mouse {
            button: VT100MouseButtonIR::Left,
            pos: TermPos::from_one_based(25, 12),
            action: VT100MouseActionIR::Scroll(crate::core::ansi::vt_100_terminal_input_parser::VT100ScrollDirectionIR::Down),
            modifiers: VT100KeyModifiersIR::default(),
        }),
    ];

    eprintln!(
        "{} PTY Controller: Sending {} mouse event sequences...",
        GLYPH_WAITING,
        mouse_events.len()
    );

    for (desc, event) in &mouse_events {
        let sequence = generate_keyboard_sequence(event)
            .unwrap_or_else(|| panic!("Failed to generate sequence for: {desc}"));
        eprintln!("  → Sending: {desc} ({sequence:?})");

        writer
            .write_all(&sequence)
            .expect("Failed to write sequence");
        writer.flush().expect("Failed to flush");
        // Read responses until we get a mouse event line. The controlled process
        // responds immediately after receiving input, so blocking reads work.
        let event_line = child.read_line_state(&mut buf_reader, |line| line.starts_with("Mouse:"));
        eprintln!("  {GLYPH_SUCCESS} {desc}: {event_line}");
    }

    eprintln!("{GLYPH_CONTROLLER_CLEANUP} PTY Controller: Cleaning up...");

    drop(writer);
    child.drain_and_wait(buf_reader, pty_pair);

    eprintln!("{GLYPH_SUCCESS} PTY Controller: Test passed!");
}

/// [`PTY`] Controlled: Read and parse mouse events. The harness performs
/// [`std::process::exit(0)`] after this function returns.
///
/// [`PTY`]: https://en.wikipedia.org/wiki/Pseudoterminal
fn controlled() {
    // Print to stdout immediately to confirm controlled is starting.
    println!("{MSG_TEST_RUNNING}");
    println!("{MSG_CONTROLLED_STARTING}");
    std::io::stdout().flush().expect("Failed to flush");

    let runtime = tokio::runtime::Runtime::new().expect("Failed to create Tokio runtime");

    runtime.block_on(async {
        eprintln!("{GLYPH_CONTROLLED} PTY Controlled: Starting...");
        let mut input_device = DirectToAnsiInputDevice::new()
            .expect("Failed to initialize DirectToAnsiInputDevice");
        eprintln!("{GLYPH_CONTROLLED} PTY Controlled: Device created, reading events...");

        // Signal to controller that we're ready to receive input. MUST be after
        // DirectToAnsiInputDevice::new() so the mio poller thread is already
        // watching stdin before the controller sends any input through the PTY.
        println!("{MSG_CONTROLLED_READY}");
        std::io::stdout().flush().expect("Failed to flush");

        let inactivity_timeout = Duration::from_secs(5);
        let mut inactivity_deadline = tokio::time::Instant::now() + inactivity_timeout;
        let mut event_count = 0;

        loop {
            tokio::select! {
                event_result = input_device.next() => {
                    match event_result {
                        Some(event) => {
                            event_count += 1;
                            inactivity_deadline = tokio::time::Instant::now() + inactivity_timeout;
                            eprintln!("{GLYPH_CONTROLLED} PTY Controlled: Event #{event_count}: {event:?}");

                            let output = match event {
                                InputEvent::Mouse(ref mouse_input) => {
                                    format!("Mouse: {mouse_input:?}")
                                }
                                _ => {
                                    format!("Event: {event:?}")
                                }
                            };

                            println!("{output}");
                            std::io::stdout().flush().expect("Failed to flush stdout");

                            if event_count >= 6 {
                                eprintln!("{GLYPH_CONTROLLED} PTY Controlled: Processed {event_count} events, exiting");
                                break;
                            }
                        }
                        None => {
                            eprintln!("{GLYPH_CONTROLLED} PTY Controlled: EOF reached");
                            break;
                        }
                    }
                }
                () = tokio::time::sleep_until(inactivity_deadline) => {
                    eprintln!("{GLYPH_CONTROLLED} PTY Controlled: Inactivity timeout (5 seconds with no events), exiting");
                    break;
                }
            }
        }

        eprintln!("{GLYPH_CONTROLLED} PTY Controlled: Completed, exiting");
    });
}
