// Copyright (c) 2025 R3BL LLC. Licensed under Apache License, Version 2.0.

// cspell:words SIGABRT ONLCR waitpid

//! This integration test verifies that [`Readline::drop()`] is resilient to mutex
//! poisoning.
//!
//! # Why [`PTY`] isolation?
//!
//! It uses [`PTY`] isolation because [`Readline::drop()`] unconditionally calls
//! [`disable_raw_mode()`].
//!
//! > This test is not using a [`PTY`] because of mock I/O devices (those work fine in
//! > normal unit tests).
//!
//! [`disable_raw_mode()`] modifies the global [`SAVED_TERMIOS`] static and alters the
//! terminal settings (specifically the [`ONLCR`] flag) of the process that runs it.
//! Without [`PTY`] isolation, this test would mutate the `cargo test` runner's own
//! terminal, causing the "staircase effect" (newlines moving the cursor down but not back
//! to column 0) in the test output.
//!
//! By running the test in a [`PTY`], [`disable_raw_mode()`] only affects the child
//! process's [`TTY`], leaving the developer's terminal environment untouched.
//!
//! # How it works
//!
//! 1. The `controlled` process poisons a mutex used by [`Readline`].
//! 2. It then triggers a panic inside [`catch_unwind`].
//! 3. During the unwind, [`Readline::drop()`] is called.
//! 4. [`drop()`] attempts to lock the poisoned mutex.
//!   - If [`drop()`] is poison-safe (uses [`into_inner()`]), it restores the terminal and
//!     returns.
//!   - If [`drop()`] is NOT poison-safe (uses `mutex.lock().unwrap()`), a **Double Panic
//!     Abort** occurs, and the process exits with [`SIGABRT`] (134).
//!
//! # Run with:
//!
//! ```bash
//! cargo test -p r3bl_tui test_double_panic_prevention -- --nocapture
//! ```
//!
//! [`disable_raw_mode()`]: crate::disable_raw_mode
//! [`drop()`]: Readline::drop()
//! [`into_inner()`]: std::sync::Mutex::into_inner
//! [`ONLCR`]: https://man7.org/linux/man-pages/man4/tty_ioctl.4.html
//! [`PTY`]: https://en.wikipedia.org/wiki/Pseudoterminal
//! [`Readline::drop()`]: Readline::drop()
//! [`SAVED_TERMIOS`]: crate::terminal_raw_mode::raw_mode_unix::SAVED_TERMIOS
//! [`SIGABRT`]: https://man7.org/linux/man-pages/man7/signal.7.html
//! [`TTY`]: crate::core::pty::pty_engine::pty_pair#what-is-a-tty

use crate::{CaughtPanicResult, ChannelCapacity, GLYPH_CONTROLLED, GLYPH_CONTROLLER,
            GLYPH_FAILURE, GLYPH_SUCCESS, InputDevice, OutputDevice, OutputDeviceExt,
            PtyTestContext, PtyTestMode, Readline, extract_panic_message,
            generate_pty_test, height, width};
use std::{panic::catch_unwind, process::exit};
use tokio::sync::broadcast;

generate_pty_test! {
    test_fn: test_double_panic_prevention,
    controller: controller,
    controlled: controlled,
    mode: PtyTestMode::Raw,
}

fn controller(context: PtyTestContext) {
    let PtyTestContext {
        pty_pair,
        child,
        buf_reader,
        ..
    } = context;

    eprintln!("{GLYPH_CONTROLLER} Controller: Waiting for child to exit...");

    // Wait for the child process to exit.
    // If double-panic happened, it will exit with SIGABRT (134).
    // If prevention worked, it will exit with code 0 (since we catch the panic).
    let exit_code = child.drain_and_wait(buf_reader, pty_pair);

    eprintln!("{GLYPH_CONTROLLER} Controller: Child exited with code: {exit_code}");

    match exit_code {
        // Generated by controlled()
        0 => {
            eprintln!(
                "{GLYPH_SUCCESS} Test Passed: Child exited with code 0 \
                (Double-Panic prevented)"
            );
        }
        // Generated by controlled()
        1 => {
            panic!(
                "{GLYPH_FAILURE} Test Failed: Child exited with code 1 \
                (second panic never triggered - controlled() test logic broken)"
            );
        }
        // Exit code 134 = 128 + SIGABRT(6) generated by the OS. A process killed by
        // signal N is reported as 128 + N by the shell/waitpid convention. The Rust
        // runtime calls abort() (which raises SIGABRT) when a panic occurs during an
        // existing unwind - i.e., the double-panic this test is designed to detect. We
        // never exit(134) ourselves.
        134 => {
            panic!(
                "{GLYPH_FAILURE} Test Failed: Child exited with SIGABRT \
                (Double-Panic occurred)"
            );
        }
        // Unexpected exit code, generated by OS.
        other => {
            panic!(
                "{GLYPH_FAILURE} Test Failed: Child exited with unexpected code: {other}"
            );
        }
    }
}

/// The harness performs [`std::process::exit(0)`] after this function returns.
fn controlled() {
    let outer_result = catch_unwind(|| {
        let (output_device, _) = OutputDevice::new_mock();
        let input_device = InputDevice::new_mock(smallvec::smallvec![]);
        let (shutdown_sender, _) = broadcast::channel::<()>(1);
        let test_size = width(100) + height(100);

        let (readline, _) = Readline::try_new(
            "> ".into(),
            output_device,
            input_device,
            shutdown_sender,
            ChannelCapacity::Minimal,
            test_size,
        )
        .expect("Failed to create Readline");

        // 1. Poison the internal safe_line_state mutex.
        let join_handle = std::thread::spawn({
            let safe_line_state = readline.safe_line_state.clone();
            move || {
                // Get the lock from mutex & hold it.
                let _guard = safe_line_state.lock().expect("Failed to lock");
                // Induce panic, which poisons the mutex.
                panic!("Poisoning safe_line_state");
            }
        });

        // Verify that the thread panicked.
        let inner_result: CaughtPanicResult = join_handle.join();
        let err_msg = extract_panic_message(inner_result);
        assert_eq!(err_msg, "Poisoning safe_line_state");

        // Verify mutex is poisoned.
        assert!(readline.safe_line_state.lock().is_err());

        eprintln!(
            "{GLYPH_CONTROLLED} Controlled: Mutex poisoned. Triggering second panic..."
        );

        // 2. Trigger a second panic.
        // During unwind, drop(readline) will be called.
        // drop(readline) will try to lock(safe_line_state) which is poisoned.
        panic!("Second panic triggering drop()");
    });

    // 3. Verify we didn't abort.
    if outer_result.is_err() {
        eprintln!(
            "{GLYPH_CONTROLLED} Controlled: Caught second panic. Exiting with code 0."
        );
        exit(0);
    } else {
        eprintln!("{GLYPH_FAILURE} Controlled: Second panic was NOT triggered!");
        exit(1);
    }
}
