// Copyright (c) 2025 R3BL LLC. Licensed under Apache License, Version 2.0.

// cspell:words SIGABRT ONLCR waitpid

//! This integration test verifies that [`Readline::drop()`] is resilient to mutex
//! poisoning.
//!
//! # Why process isolation?
//!
//! It uses process isolation because [`Readline::drop()`] unconditionally calls
//! [`disable_raw_mode()`].
//!
//! > This test does not use a [`PTY`] because mock I/O devices are used (which work fine
//! > in normal unit tests).
//!
//! [`disable_raw_mode()`] modifies the global [`SAVED_TERMIOS`] static and alters the
//! terminal settings (specifically the [`ONLCR`] flag) of the process that runs it.
//! Without process isolation, this test would mutate the `cargo test` runner's own
//! terminal, causing the "staircase effect" (newlines moving the cursor down but not back
//! to column 0) in the test output.
//!
//! By running the test in an isolated process, [`disable_raw_mode()`] only affects the
//! child process, leaving the developer's terminal environment untouched.
//!
//! # How it works
//!
//! 1. The `controlled` process poisons a mutex used by [`Readline`].
//! 2. It then triggers a panic inside [`catch_unwind`].
//! 3. During the unwind, [`Readline::drop()`] is called.
//! 4. [`drop()`] attempts to lock the poisoned mutex.
//!   - If [`drop()`] is poison-safe (uses [`into_inner()`]), it restores the terminal and
//!     returns.
//!   - If [`drop()`] is NOT poison-safe (uses `mutex.lock().expect("conversion error")`),
//!     a **Double Panic Abort** occurs, and the process terminates abnormally.
//!
//! # Run with:
//!
//! ```bash
//! cargo test -p r3bl_tui test_double_panic_prevention -- --nocapture
//! ```
//!
//! [`disable_raw_mode()`]: crate::disable_raw_mode
//! [`drop()`]: Readline::drop()
//! [`into_inner()`]: std::sync::Mutex::into_inner
//! [`ONLCR`]: https://man7.org/linux/man-pages/man4/tty_ioctl.4.html
//! [`PTY`]: https://en.wikipedia.org/wiki/Pseudoterminal
//! [`Readline::drop()`]: Readline::drop()
//! [`SAVED_TERMIOS`]: crate::terminal_raw_mode::raw_mode_unix::SAVED_TERMIOS
//! [`SIGABRT`]: https://man7.org/linux/man-pages/man7/signal.7.html
//! [`TTY`]: crate::core::pty::pty_engine::pty_pair#what-is-a-tty

use crate::{CaughtPanicResult, ChannelCapacity, GLYPH_CONTROLLED, GLYPH_CONTROLLER,
            GLYPH_FAILURE, GLYPH_SUCCESS, InputDevice, OutputDevice, OutputDeviceExt,
            Readline, extract_panic_message, generate_isolated_process_test, vp_height,
            vp_width};
use std::{panic::catch_unwind, process::exit};
use tokio::sync::broadcast;

generate_isolated_process_test!(
    /// Integration test verifying that [`Readline::drop()`] is resilient to mutex
    /// poisoning.
    test_double_panic_prevention,
    controller,
    controlled,
    std::process::Stdio::null(),
    std::process::Stdio::piped(),
    std::process::Stdio::piped()
);

fn controller(spawned_self_process_output: std::process::Output) {
    let stdout = String::from_utf8_lossy(&spawned_self_process_output.stdout);
    let stderr = String::from_utf8_lossy(&spawned_self_process_output.stderr);

    eprintln!("{GLYPH_CONTROLLER} Controller: Waiting for child to exit...");
    if !stdout.is_empty() {
        eprintln!("  child stdout: {stdout}");
    }
    if !stderr.is_empty() {
        eprintln!("  child stderr: {stderr}");
    }

    let status = spawned_self_process_output.status;
    eprintln!("{GLYPH_CONTROLLER} Controller: Child exited with status: {status:?}");

    #[cfg(unix)]
    {
        use std::os::unix::process::ExitStatusExt;
        if let Some(signal) = status.signal() {
            assert!(
                signal != signal_hook::consts::SIGABRT,
                "{GLYPH_FAILURE} Test Failed: Child exited with SIGABRT \
                (Double-Panic occurred)"
            );
            panic!("{GLYPH_FAILURE} Test Failed: Child terminated by signal: {signal}");
        }
    }

    match status.code() {
        // Generated by controlled()
        Some(0) => {
            eprintln!(
                "{GLYPH_SUCCESS} Test Passed: Child exited with code 0 \
                (Double-Panic prevented)"
            );
        }
        // Generated by controlled()
        Some(1) => {
            panic!(
                "{GLYPH_FAILURE} Test Failed: Child exited with code 1 \
                (second panic never triggered: controlled() test logic broken)"
            );
        }
        // Unexpected exit code.
        Some(other) => {
            panic!(
                "{GLYPH_FAILURE} Test Failed: Child exited with unexpected code: {other}"
            );
        }
        None => {
            panic!(
                "{GLYPH_FAILURE} Test Failed: Child terminated abnormally: {status:?}"
            );
        }
    }
}

/// The harness performs [`std::process::exit(0)`] after this function returns.
fn controlled() {
    let outer_result = catch_unwind(|| {
        let (output_device, _) = OutputDevice::new_mock();
        let input_device = InputDevice::new_mock(smallvec::smallvec![]);
        let (shutdown_sender, _) = broadcast::channel::<()>(1);
        let test_size = vp_width(100) + vp_height(100);

        let (readline, _) = Readline::try_new(
            "> ".into(),
            output_device,
            input_device,
            shutdown_sender,
            ChannelCapacity::Minimal,
            test_size,
        )
        .expect("Failed to create Readline");

        // 1. Poison the internal safe_line_state mutex.
        let join_handle = std::thread::spawn({
            let safe_line_state = readline.safe_line_state.clone();
            move || {
                // Get the lock from mutex & hold it.
                safe_line_state.write(|_| {
                    // Induce panic, which poisons the mutex.
                    panic!("Poisoning safe_line_state");
                });
            }
        });

        // Verify that the thread panicked.
        let inner_result: CaughtPanicResult = join_handle.join();
        let err_msg = extract_panic_message(inner_result);
        assert_eq!(err_msg, "Poisoning safe_line_state");

        // Verify mutex is poisoned.
        assert!(readline.safe_line_state.lock_raw(|result| result.is_err()));

        eprintln!(
            "{GLYPH_CONTROLLED} Controlled: Mutex poisoned. Triggering second panic..."
        );

        // 2. Trigger a second panic.
        // During unwind, drop(readline) will be called.
        // drop(readline) will try to lock(safe_line_state) which is poisoned.
        panic!("Second panic triggering drop()");
    });

    // 3. Verify we didn't abort.
    if outer_result.is_err() {
        eprintln!(
            "{GLYPH_CONTROLLED} Controlled: Caught second panic. Exiting with code 0."
        );
        exit(0);
    }

    eprintln!("{GLYPH_FAILURE} Controlled: Second panic was NOT triggered!");
    exit(1);
}
