# cspell:words incompat

# Compiler and Linker Speedups:
# 1. Parallel frontend compiler (`-Z threads=8`)
# 2. fast `rust-lld` linker on Linux (`link-arg=-fuse-ld=lld)
# Requires nightly toolchain (see rust-toolchain.toml).
# Tracking issue: https://github.com/rust-lang/rust/issues/113349
[target.'cfg(target_os = "linux")']
rustflags = ["-Z", "threads=8", "-C", "link-arg=-fuse-ld=lld"]

[build]
# Store build artifacts in tmpfs for maximum compile performance
target-dir = "/tmp/roc/target"

[profile.dev]
# Only disable to avoid rustc dep graph ICE on nightly which should not
# happen due to rust-toolchain-update.fish
incremental = true

[profile.test]
# Only disable to avoid rustc dep graph ICE on nightly which should not
# happen due to rust-toolchain-update.fish
incremental = true
