# cspell:words incompat

# Compiler and Linker Speedups:
# 1. Parallel frontend compiler (`-Z threads=8`)
# 2. Fast bundled `rust-lld` linker (`-C linker-features=+lld`)
# Requires nightly toolchain (see rust-toolchain.toml).
# Tracking issue: https://github.com/rust-lang/rust/issues/113349
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Z", "threads=8", "-Z", "unstable-options", "-C", "linker-features=+lld"]

[profile.dev]
# Only disable to avoid rustc dep graph ICE on nightly which should not
# happen due to rust-toolchain-update.fish
incremental = true

[profile.test]
# Only disable to avoid rustc dep graph ICE on nightly which should not
# happen due to rust-toolchain-update.fish
incremental = true
