// Copyright (c) 2025 R3BL LLC. Licensed under Apache License, Version 2.0.

//! # [`PTY`] Module
//!
//! This module provides a high-level, async interface for spawning and controlling
//! processes in [pseudoterminals] ([`PTY`]s). It is designed to be the foundational
//! engine for terminal multiplexers (like [`tmux`]), interactive shells, and TUI
//! applications.
//!
//! ## The Developer's Journey
//!
//! Imagine you're building a terminal multiplexer (like [`tmux`]), or a coding agent
//! (like [`gemini-cli`]) in which you must run programs and capture their output while
//! providing them input (and these programs must think they are running in an interactive
//! terminal). You will need to handle the following tasks:
//!
//! 1. **Spawning**: You need to start a shell process (like [`bash`]) inside a [`PTY`] so
//!    it thinks it's talking to a real terminal.
//! 2. **Orchestration**: You need to manage the lifecycle of that shell process,
//!    capturing its output while sending your keystrokes (from your app) to it (as if
//!    this input was going directly into the managed shell process).
//! 3. **Multiplexing**: You might want to provide the ability to spawn multiple shell
//!    processes, and switch between them instantly, keeping each shell's state alive even
//!    when it is not visible.
//!
//! This module provides the building blocks for this journey, organized into a
//! three-layer functional stack.
//!
//! ## The Functional Stack
//!
//! The [`PTY`] module is structured into three distinct layers of abstraction, with a 1-1
//! mapping to each step in the developer's journey shown above. However, it is inverted -
//! step 1 in the journey maps to the last layer below.
//!
//! ```text
//! ┌──────────────────────────────────────────────────────────────────────────────┐
//! │                              APPLICATION LAYER             (3. Multiplexing) │
//! │         (e.g., PTY Mux, TUI App, Terminal Emulator, readline_async App)      │
//! └──────────────────────────────────────┬───────────────────────────────────────┘
//!                                        │
//! ┌──────────────────────────────────────▼───────────────────────────────────────┐
//! │                                SESSION LAYER              (2. Orchestration) │
//! │        (Async orchestration, task management, event channels, OSC)           │
//! │              ┌───────────────────────────────────────────────┐               │
//! │              │           mod pty_session (Session layer)     │               │
//! │              └───────────────────────────────────────────────┘               │
//! └──────────────────────────────────────┬───────────────────────────────────────┘
//!                                        │
//! ┌──────────────────────────────────────▼───────────────────────────────────────┐
//! │                                 ENGINE LAYER                   (1. Spawning) │
//! │          (OS-level PTY pair creation, deadlock prevention, I/O)              │
//! │              ┌───────────────────────────────────────────────┐               │
//! │              │         mod pty_engine (PtyPair, etc.)        │               │
//! │              └───────────────────────────────────────────────┘               │
//! └──────────────────────────────────────────────────────────────────────────────┘
//! ```
//!
//! 1. **Application Layer**: This is your code. Whether it's the built-in [`PTYMux`] or
//!    your custom [`TUI`] or [`readline_async`] app, this layer consumes events from the
//!    Session Layer and sends inputs generated by the end user interacting with your app,
//!    to the Session Layer.
//! 2. **[Session Layer]**: The async orchestration layer. It bridges the gap between
//!    synchronous OS [`PTY`] I/O and your async application using [`tokio`] tasks and
//!    channels. This is where the **Task Trio** lives.
//! 3. **[Engine Layer]**: The low-level foundation. It handles the tricky business of
//!    opening OS [`PTY`] pairs and programmatically preventing deadlocks caused by leaked
//!    file descriptors. See [`PtyPair`] for details.
//!
//! ## The Life of a Session
//!
//! Understanding the lifecycle of a [`PTY`] session, from its birth to its eventual
//! teardown, is essential for building robust [`TUI`] and [`readline_async`] applications
//! (that use this [`pty` module]). This journey involves coordinated interactions across
//! all three layers of the functional stack.
//!
//! ### 1. Birth (Spawning)
//!
//! It all begins when your app ([`TUI`] or [`readline_async`]) uses
//! [`PtySessionBuilder::start()`] to start a session. This kicks off the **initialization
//! sequence** across all three layers.
//!
//! - **Session Layer**: [`PtySessionBuilder::start()`] orchestrates the entire startup.
//!   First it uses the **Engine Layer** to spawn the child process in the [`PTY`]
//!   environment, then wraps it in the **Task Trio** ([Reader], [Writer],
//!   [Orchestrator]), and finally sets up the [MPSC channels].
//! - **Engine Layer**: Called by the **Session Layer**, [`PtyPair::open_and_spawn()`]
//!   creates the OS-level [`PTY`] pair and spawns the child process. Crucially, it
//!   immediately drops the parent's copy of the **controlled** file descriptor to prevent
//!   [resource-leaking deadlocks] at birth.
//! - **App Layer**: Once the initialization sequence is complete, your application
//!   receives a [`PtySession`] handle, ready to begin interaction.
//!
//! ### 2. Life (Interaction)
//!
//! Once the session is running, and your app is running, a balanced bidirectional data
//! flow begins.
//!
//! - **App Layer**: Sends to the session and receives events from it:
//!   - Sends [`PtyInputEvent`]s, e.g., keyboard input, and resize requests. See
//!     [`ProcessManager::send_input()`] and [`ProcessManager::handle_terminal_resize()`])
//!     for examples.
//!   - Receives [`PtyOutputEvent`]s, e.g., process output, [`OSC`] sequences, and exit
//!     status. See [`ProcessManager::poll_all_processes()`]) for examples.
//! - **Session Layer**: The task trio works to connect the app layer to the engine.
//!   - The [Writer Task] (blocking) pumps input events to the engine.
//!   - The [Reader Task] (blocking) drains output from the engine.
//!   - The [Orchestrator Task] (async) monitors the child process's lifecycle.
//! - **Engine Layer**: Manages the low-level [`Controller`] and **controlled** process
//!   I/O.
//!
//! ### 3. The Great Beyond (Teardown & Cleanup)
//!
//! A session can end in two ways: gracefully (initiated by the child) or forcefully
//! (initiated by your app).
//!
//! #### Child-Initiated (Graceful Exit)
//!
//! 1. **Child Process Exits**: The process running inside the [`PTY`] (e.g., a shell
//!    after an `exit` command) terminates.
//! 2. **Engine Layer**: The OS closes the **controlled** side of the [`PTY`]. Because
//!    [`PtyPair`] already dropped its copy of the controlled FD at birth, the kernel's
//!    reference count hits zero.
//! 3. **Signal**: The kernel sends a termination signal—[`EOF`] (or [`EIO`] on Linux)—to
//!    the [`Controller`] reader.
//! 4. **Session Layer**:
//!    - The [Reader Task] sees this signal and exits cleanly.
//!    - The [Orchestrator Task] (which was awaiting [`ControlledChild::wait()`]) detects
//!      the exit.
//!    - It joins both the [Reader] and [Writer] tasks to ensure all I/O is drained.
//!    - Finally, it sends a [`PtyOutputEvent::Exit`] event to the App.
//!
//! #### App-Initiated (Forced Shutdown)
//!
//! When your application needs to shut down (e.g., the user quits your app), it should
//! follow this **Critical Shutdown Pattern**:
//!
//! 1. **Kill**: Forcefully terminate the child process using the
//!    [`PtySession::child_process_termination_handle`].
//! 2. **Close**: Send a [`PtyInputEvent::Close`] to signal the [Writer Task] to stop.
//! 3. **Drop**: Drop the [`PtySession`] handle.
//!
//! #### The Final Cleanup (RAII and the Drop Chain)
//!
//! When your app drops the [`PtySession`] handle, Rust's automatic resource management
//! ([RAII]) triggers a cleanup chain across all internal components:
//!
//! - **Session Layer**:
//!   - The [MPSC channels] are closed when their halves are dropped.
//!   - The task trio join handles are dropped in a cascading chain:
//!     - [`PtySession`] drops the [Orchestrator Task] handle.
//!     - The Orchestrator, in turn, drops its internal [Reader Task] and [Writer Task]
//!       handles.
//! - **Engine Layer**:
//!   - The [`Controller`] (from the [Engine Layer]) is dropped.
//!   - The [`PtyPair`] (and its inner [`MasterPty`]) leverages [RAII] to guarantee that
//!     all OS-level file descriptors are closed. This eliminates the risk of
//!     [resource-leaking deadlocks] and ensures a clean system state.
//!
//! ## The Task Trio
//!
//! Every active [`PTY`] session is powered by a set of specialized tasks (the **Task
//! Trio**).
//!
//! | Task             | Role             | Type         | Responsibility                                                                                            |
//! | :--------------- | :--------------- | :----------- | :-------------------------------------------------------------------------------------------------------- |
//! | **Reader**       | 📥 [`PTY`] ➜ App | **Blocking** | [`spawn_blocking_reader_task()`]: Reads raw bytes, processes [`OSC`], sends events to App.                |
//! | **Writer**       | 📤 App ➜ [`PTY`] | **Blocking** | [`spawn_blocking_writer_task()`]: Receives input events from App and writes them to [`stdin`].            |
//! | **Orchestrator** | 🏁 Lifecycle     | **Async**    | [`spawn_orchestrator_task()`]: Manages child process, waits for exit, and coordinates shutdown.           |
//!
//! ## Technical Deep Dive
//!
//! ### Session Architecture
//!
//! The **Task Trio** provides bidirectional communication between your app and the child
//! process.
//!
//! ```text
//!        ┌───────────────────────────────────────────────────────────────────────┐
//! ┌──────▼───────┐   ┌──────────────────────────────────────────┐                │
//! │ Your Program │   │           Orchestrator Task (1)          │                │
//! │ (App Layer)  │   │            ↙               ↘             │                │
//! │ Sends Input  ├───► Writer Task (3)         Reader Task (2)  ── Sends Output ─┘
//! │ Events       │   │ (App → PTY)             (PTY → App)      │  Events
//! │              │   └──────┬────────────────────────────▲──────┘
//! │              │          │                            │
//! │              │   ┌──────▼────────────────────────────┴──────┐
//! │              │   │ ┊Controller┊  ← PTY Pair →  ┊Controlled┊ │
//! └──────────────┘   └──────┬────────────────────────────▲──────┘
//!                           │                            │
//!                    ┌──────▼────────────────────────────┴──────┐
//!                    │            Child Process                 │
//!                    └──────────────────────────────────────────┘
//! Legends:
//! (1): The **Orchestrator** task - spawns other tasks, manages lifecycle and shutdown.
//! (2): The **Reader** task - reads output from PTY and sends events to App.
//! (3): The **Writer** task - receives input from App and writes to PTY.
//! ```
//!
//! ### Task Coordination & Lifecycle
//!
//! | Time | Orchestrator Task                   | Reader Task      | Writer Task         |
//! | :--- | :---------------------------------- | :--------------- | :------------------ |
//! | 0    | 🛫 Spawn child                      |                  |                     |
//! | 1    | 🛫 Spawn tasks                      | 🛫 Start read    | 🛫 Start            |
//! | 2    | 🛬 Wait [`ControlledChild::wait()`] | 📖 Read data     | 📥 Wait input       |
//! | 3    | 🛬 Wait tasks                       | 🛬 Exit (on EOF) | 🛬 Exit (on Close)  |
//! | 4    | 📤 Send Exit event                  |                  |                     |
//! | 5    | ✅ Return status                    |                  |                     |
//!
//! Legends:
//! ```txt
//! Task lifecycle:    🛫 start  | 🛬 wait/exit | ✅ done
//! IO operations:     📖 read   | ✍️ write
//! Send/receive pair: 📤 send   | 📥 receive
//! ```
//!
//! ### Channel Architecture
//!
//! ```text
//! Your Program
//!      │
//!      │ (async input)
//!      │
//! ┌────▼────────────────────────────────┐
//! │    Async Input Channel              │
//! │    (bounded MPSC)                   │
//! └─────────────────────────────────────┘
//!      │
//!      │ (Writer Task - blocking)
//!      │
//! ┌────▼────────────────────────────────┐
//! │    PTY Controller                   │
//! │    (write to spawned)               │
//! └─────────────────────────────────────┘
//!      │
//! ┌────▼────────────────────────────────┐
//! │    Spawned Process Input            │
//! └─────────────────────────────────────┘
//!
//! ──── Spawned process boundary ────────
//!
//! ┌─────────────────────────────────────┐
//! │    Spawned Process Output           │
//! └─────────────────────────────────────┘
//!      │
//!      │
//! ┌────▼────────────────────────────────┐
//! │    PTY Controller                   │
//! │    (read from spawned)              │
//! └─────────────────────────────────────┘
//!      │
//!      │ (Reader Task - blocking)
//!      │
//! ┌────▼────────────────────────────────┐
//! │     Async Output Channel            │
//! │     (bounded MPSC)                  │
//! └─────────────────────────────────────┘
//!      │
//!      │ (async output)
//!      │
//!      ▼
//! Your Program
//! ```
//!
//! ## Main Types
//!
//! - [`PtySessionBuilder`]: Builder for configuring and starting sessions via
//!   [`start()`].
//! - [`PtySession`]: [`PTY`] session handle.
//! - [`PtyOutputEvent`]: Unified events received from [`PTY`] processes.
//! - [`PtyInputEvent`]: Input types that can be sent to interactive sessions.
//!
//! [`bash`]: https://www.gnu.org/software/bash/
//! [`ControlledChild::wait()`]: portable_pty::Child::wait
//! [`EIO`]: https://man7.org/linux/man-pages/man3/errno.3.html
//! [`EOF`]: https://en.wikipedia.org/wiki/End-of-file
//! [`gemini-cli`]: https://github.com/google-gemini/gemini-cli
//! [`MasterPty`]: portable_pty::MasterPty
//! [`OSC`]: crate::osc_codes::OscSequence
//! [`ProcessManager::handle_terminal_resize()`]:
//!     crate::ProcessManager::handle_terminal_resize
//! [`ProcessManager::poll_all_processes()`]: crate::ProcessManager::poll_all_processes
//! [`ProcessManager::send_input()`]: crate::ProcessManager::send_input
//! [`pty` module]: mod@crate::core::pty
//! [`PTY`]: https://en.wikipedia.org/wiki/Pseudoterminal
//! [`PtyInputEvent`]: crate::PtyInputEvent
//! [`PTYMux`]: crate::PTYMux
//! [`PtyOutputEvent::Exit`]: crate::PtyOutputEvent::Exit
//! [`PtyOutputEvent`]: crate::PtyOutputEvent
//! [`PtyPair::open_and_spawn()`]: crate::PtyPair::open_and_spawn
//! [`PtyPair`]: crate::PtyPair
//! [`PtySession::child_process_termination_handle`]:
//!     field@crate::PtySession::child_process_termination_handle
//! [`PtySession`]: crate::PtySession
//! [`PtySessionBuilder::start()`]: crate::PtySessionBuilder::start
//! [`PtySessionBuilder`]: crate::PtySessionBuilder
//! [`readline_async`]: crate::readline_async::ReadlineAsyncContext::try_new
//! [`spawn_blocking_reader_task()`]:
//!     crate::pty_session::tasks::reader_task::spawn_blocking_reader_task
//! [`spawn_blocking_writer_task()`]:
//!     crate::pty_session::tasks::writer_task::spawn_blocking_writer_task
//! [`spawn_orchestrator_task()`]:
//!     crate::pty_session::tasks::orchestrator::spawn_orchestrator_task
//! [`start()`]: [`PtySessionBuilder::start()`]
//! [`stdin`]: std::io::Stdin
//! [`tmux`]: https://github.com/tmux/tmux
//! [`tokio`]: tokio
//! [`TUI`]: crate::tui::TerminalWindow::main_event_loop
//! [Engine Layer]: crate::pty_engine
//! [MPSC channels]: tokio::sync::mpsc
//! [Orchestrator Task]: crate::pty_session::tasks::orchestrator::spawn_orchestrator_task
//! [Orchestrator]: crate::pty_session::tasks::orchestrator::spawn_orchestrator_task
//! [pseudoterminals]: https://en.wikipedia.org/wiki/Pseudoterminal
//! [RAII]: https://en.cppreference.com/w/cpp/language/raii
//! [Reader Task]: crate::pty_session::tasks::reader_task::spawn_blocking_reader_task
//! [Reader]: crate::pty_session::tasks::reader_task::spawn_blocking_reader_task
//! [resource-leaking deadlocks]:
//!     crate::pty_engine::pty_pair::PtyPair#resource-leaking-deadlock
//! [Session Layer]: crate::pty_session
//! [Session layer]: crate::pty_session
//! [Writer Task]: crate::pty_session::tasks::writer_task::spawn_blocking_writer_task
//! [Writer]: crate::pty_session::tasks::writer_task::spawn_blocking_writer_task

#![rustfmt::skip]

// Attach.
pub mod pty_engine;
pub mod pty_mux;
pub mod pty_session;

#[cfg(test)]
mod e2e_tests;

// Re-export.
pub use pty_engine::*;
pub use pty_mux::*;
pub use pty_session::*;

// Rustdoc search link fixes.

#[doc(inline)] // Create doc pages at re-export path so rustdoc search links resolve.
pub use pty_session::{pty_input_event, pty_output_event, pty_session_builder,
                      pty_session_types, tasks};
